FROM python:3.11-slim

WORKDIR /app

COPY ./src /app/src

COPY ./telegram_bot /app/telegram_bot

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv
COPY ./pyproject.toml ./uv.lock ./

RUN apt-get update && apt-get install -y \
    gcc \
    libsqlite3-dev \
    build-essential

RUN uv sync --frozen --no-dev

ENV PYTHONPATH=/app

CMD ["bash", "-c", "python src/database_utils/init_db.py && python telegram_bot/run_bot.py"]
