FROM ollama/ollama:latest

USER root
RUN apt-get update && apt-get install -y bash curl && rm -rf /var/lib/apt/lists/*

COPY ./entrypoints/ollama_entrypoint.sh ollama_entrypoint.sh
RUN chmod +x ollama_entrypoint.sh

ENTRYPOINT ["/ollama_entrypoint.sh"]
