FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY src /app/src
COPY telegram_bot /app/telegram_bot
COPY queue_svc /app/queue_svc

COPY --from=ghcr.io/astral-sh/uv:0.9.0 /uv /usr/local/bin/uv
COPY ./pyproject.toml ./uv.lock ./
RUN uv sync --frozen --no-dev

ENV PYTHONPATH=/app

CMD ["sleep", "infinity"]
