FROM python:3.11-slim

WORKDIR /app

COPY ./src /app/src

COPY ./web_app /app/web_app

RUN apt-get update && apt-get install -y \
    gcc \
    libsqlite3-dev \
    build-essential

COPY --from=ghcr.io/astral-sh/uv:0.9.0 /uv /usr/local/bin/uv
COPY ./pyproject.toml ./uv.lock /app/
RUN uv sync --frozen --no-dev

EXPOSE 8000

ENV PYTHONPATH=/app

CMD ["uv", "run", "bash", "-c", "python web_app/main.py"]