version: '3.9'

x-common-env: &common-env
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_DB: ${POSTGRES_DB}

x-stdout-file-logging: &stdout-file-logging
  driver: "local"
  options:
    max-size: "10m"
    max-file: "5"


services:

  web_app:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: web_app
    volumes:
      - ./src/db:/app/src/db
    ports:
      - "8000:8000"
    environment:
      CIPHER_KEY: ${CIPHER_KEY}
      RENDER_EXTERNAL_URL: ${RENDER_EXTERNAL_URL}
      <<: *common-env
    depends_on:
      postgres_db:
        condition: service_healthy
      telegram_bot:
        condition: service_started
    logging: *stdout-file-logging


  telegram_bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: telegram_bot
    volumes:
      - ./src/db:/app/src/db
    environment:
      CIPHER_KEY: ${CIPHER_KEY}
      BOT_TOKEN: ${BOT_TOKEN}
      RENDER_EXTERNAL_URL: ${RENDER_EXTERNAL_URL}
      <<: *common-env
    depends_on:
      postgres_db:
        condition: service_healthy
    logging: *stdout-file-logging


  postgres_db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      <<: *common-env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user"]
      interval: 5s
      timeout: 3s
      retries: 10
    logging: *stdout-file-logging

  ollama:
      build:
        context: .
        dockerfile: Dockerfile.ollama
      container_name: ollama
      restart: unless-stopped
      volumes:
        - ./ollama_data:/root/.ollama
      environment:
        OLLAMA_HOST: 0.0.0.0
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
        interval: 10s
        timeout: 5s
        retries: 5
      # ports:
      # - "11434:11434"   # just for testing
      logging: *stdout-file-logging

  queue:
    build:
      context: .
      dockerfile: Dockerfile.queue
    container_name: queue
    restart: unless-stopped
    command:
      - python
      - -m
      - queue_svc.main
    environment:
      <<: *common-env
      # INTERVAL_SECONDS: ${INTERVAL_SECONDS:-7200}
      BOT_TOKEN: ${BOT_TOKEN}
    depends_on:
      postgres_db:
        condition: service_healthy
    logging: *stdout-file-logging
