FROM python:3.11-slim

WORKDIR /app

COPY ./src /app/src

COPY ./web_app /app/web_app

COPY ./requirements.txt /app

RUN apt-get update && apt-get install -y \
    gcc \
    libsqlite3-dev \
    build-essential

RUN pip install -r requirements.txt

EXPOSE 8000

ENV PYTHONPATH=/app

CMD ["sh", "-c", "cd web_app && python main.py"]