services:
  web_app:
    build:
      context: .
      dockerfile: Dockerfile.web
    volumes:
      - ./src:/app/src
    image: kipariss/czech_out_auto_bot_webapp:latest
    working_dir: /app
    ports:
      - "8000:8000"


  