"""add parsed advertisement cache

Revision ID: f6991f02cd0d
Revises: 54e2c7c7af01
Create Date: 2026-07-12 20:56:38.428933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6991f02cd0d'
down_revision: Union[str, Sequence[str], None] = '54e2c7c7af01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Parsed_Advertisements_Cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bazos_id', sa.BIGINT(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('parsed_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['Car_Models.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bazos_id', 'car_id', name='uq_parsed_ad_cache_bazos_car')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Parsed_Advertisements_Cache')
    # ### end Alembic commands ###
